.PHONY: fmt
fmt:
	bash fmt.sh

.PHONY: doc
doc:
	doxygen Doxyfile
	$(MAKE) -C doxygen.out.d/latex

.PHONY: autotools
autotools:
	autoreconf -if -Wall
	mkdir -p autotools
	cd autotools && ../configure

.PHONY: build
build:
	mkdir -p build && \
	cd build && \
	cmake -Wdev -Wdeprecated --warn-uninitialized -DCMAKE_BUILD_TYPE=Debug .. && \
	cmake --build . --clean-first --parallel 40 && \
	ctest
