// On following code 1 indicates success.
#define CEU_HAVE_SNPRINTF 0
#define CEU_HAVE__SNPRINTF 1
#define CEU_HAVE_INCLUDE_STDBOOL_H 0
#define CEU_HAVE_INCLUDE_VERSIONHELPERS_H 0

// On following code 0 indicates success.
#define CEU_CM_HAVE_WORKING_C__BOOL_RUN_STATIC 1
#define CEU_CM_HAVE_WORKING_C__BOOL_RUN_SHARED 1
#define CEU_CM_HAVE_WORKING_C_INLINE_RUN_STATIC 1
#define CEU_CM_HAVE_WORKING_C_INLINE_RUN_SHARED 1
#define CEU_CM_HAVE_WORKING_C___INLINE_RUN_STATIC 0
#define CEU_CM_HAVE_WORKING_C___INLINE_RUN_SHARED 1
