set(CEU_LIBRARY_SHARED ceu_shared)
set(CEU_LIBRARY_STATIC ceu_static)
set(CEU_LIBRARY_SHARED_CXX ceu_shared_cxx)
set(CEU_LIBRARY_STATIC_CXX ceu_static_cxx)
include_directories(${CMAKE_CURRENT_LIST_DIR}/../include/)
