include("${CMAKE_CURRENT_LIST_DIR}/libcmake/enhanced_find.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/libcmake/enhanced_try_run.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/libcmake/print_test_status.cmake")

ceu_enhanced_find_library(OUTPUT_VARIABLE LIBLZMA_LIBRARY_SHARED PKGCONFIG_NAME liblzma LINKER_FLAG lzma)
ceu_enhanced_find_library(STATIC OUTPUT_VARIABLE LIBLZMA_LIBRARY_STATIC PKGCONFIG_NAME liblzma LINKER_FLAG lzma)

if (LIBLZMA_LIBRARY_SHARED)
    enhanced_try_run(VARNAME LIBLZMA SRC_PATH "test_liblzma.c" LINK_LIBRARIES "${LIBLZMA_LIBRARY_SHARED}")
else ()
    set(HAVE_WORKING_LIBLZMA_RUN_SHARED 127 CACHE INTERNAL "doc")
    set(HAVE_WORKING_LIBLZMA_COMPILE_SHARED FALSE CACHE INTERNAL "doc")
endif ()
if (LIBLZMA_LIBRARY_STATIC)
    enhanced_try_run(STATIC VARNAME LIBLZMA SRC_PATH "test_liblzma.c" LINK_LIBRARIES "${LIBLZMA_LIBRARY_STATIC}")
else ()
    set(HAVE_WORKING_LIBLZMA_RUN_STATIC 127 CACHE INTERNAL "doc")
    set(HAVE_WORKING_LIBLZMA_COMPILE_STATIC FALSE CACHE INTERNAL "doc")
endif ()

ceu_print_test_status("liblzma" LIBLZMA)
